codecov:
  branch: main
coverage:
  round: up
  range: 80..100
  precision: 2
  status:
    project:
      default:
        target: 90%
        threshold: 1%
    patch:
      default:
        target: 90%
        threshold: 1%
ignore:
  - conftest.py
  - fuzzbucket_client/__version__.py
  - setup.py
