[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"

[tool.black]
extend-exclude = '''
__version__.py
'''

[tool.coverage.run]
omit = ["tests/*"]
branch = true

[tool.setuptools_scm]
write_to = "fuzzbucket/__version__.py"
